version: '3'
services:
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    links:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - /home/ericpinto/Desenvolvimento/Docker/Volumes/MongoDB:/data/db
  sonarqube:
    image: library/sonarqube:8.6-community
    ports:
      - "9000:9000"